version: '3'
services:
  nest:
    container_name: nest-http
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./:/app
    networks:
      default:
        ipv4_address: 172.0.35.3
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.35.0/28
